# Created by: Mark Pulford <mark@kyne.com.au>
# $FreeBSD$

PORTNAME=	throttle
PORTVERSION=	1.2
CATEGORIES=	truenas sysutils
VALID_CATEGORIES+= truenas
MASTER_SITES=	http://download.freenas.org/distfiles/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A pipe bandwidth throttling utility

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/throttle

.include <bsd.port.mk>
