#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-syncmultipaths
# REQUIRE: middlewared FILESYSTEMS ix-syncdisks

. /etc/rc.subr

syncmultipaths()
{
	echo "Syncing multipaths..."
	/usr/local/bin/midclt call disk.multipath_sync > /dev/null
}

name="ix_syncmultipaths"
start_cmd='syncmultipaths'
stop_cmd=''

load_rc_config $name
run_rc_command "$1"
